nesta:
  title: "Green Worm"
  subtitle: "W3C Standards based Web Development and Design"
  author:
    name: Ash McKenzie
    uri: http://greenworm.com.au
    email: ash@greenworm.com.au
  theme: greenworm.com.au
  cache: false
  content: content
  production:
    cache: true    
    content: /home/apps/greenworm/current/content
    google_analytics_code: "UA-8842201-1"

deploy:
  repo: 'git@github.com:ashmckenzie/greenworm-com-au.git'
  ssh_host: 'the-rebellion.net'
  ssh_user: 'apps'
  ssh_key: "File.join(ENV['HOME'], '.ssh', 'ashmckenzie_deployment_2048_rsa')"
  deploy_to: '/home/apps/greenworm'
  nginx:
    config_name: 'greenworm'
    server_name: 'greenworm.the-rebellion.net'
    root: '/home/apps/greenworm/current/public'
    log_name: 'greenworm'